### ISSUE TITLE
different navigation

### ISSUE THREAD

**Issue by ragefuljoe** [bilalakil/bin#2]
thanks for your examples, this helped immensely. Wondering if you know how to do different navigation appearance, specifically to show {current} of {total} rather than the page lists.

I'm currently just hiding the generated pagination, and binding buttons to next/prev.

**Comment by bilalakil** [comment]
Hi Joe, thanks for the kind word and for not raging ;)

Unfortunately I can't see anything in the documentation that would allow you to very easily achieve such behaviour, but if you're brave enough to tinker around you can work with the `getCurrentPage` (current) and `getPagesCount` (total) functions and render those yourself.

If you think it's a feature worth being included in the plugin, consider contributing to [its repository](https://github.com/flaviusmatis/simplePagination.js) or opening an issue there requesting it.

If you just want it made for your current needs but need help doing so, reopen this issue and ask and I'll try to find some time and whip up an example for you :) Oh, and if you end up implementing it yourself, consider commenting back here and showing us!

Good luck Joe! Let us know how you go.

**Comment by ragefuljoe** [comment]
I just bound some buttons in the html that I made, to

```
$('.rcrprev').click(function() {
                     if ($pagination.pagination("getCurrentPage") === 1) {
                         $pagination.pagination("selectPage", $pagination.pagination("getPagesCount"));
                     } else {
                         rcrchangePage('prev');
                     }
                 });


$('.rcrnext').click(function() {
             if ($pagination.pagination("getCurrentPage") === $pagination.pagination("getPagesCount")) {
                 $pagination.pagination("selectPage", 1);
             } else {
                 rcrchangePage('next');
             }
         });


function rcrchangePage(direction) {
             $pagination.pagination(direction + 'Page');
         };
```

prob some refactoring needed but it works. some extra in there to handle wrapping as well. then I set the generated pagination dom to display:none;

**Comment by bilalakil** [comment]
That's pretty cool! Here's a nice way to reduce a lot of the repetition in `$pagination.pagination` you've got there:

```
(function() {
    var pnator = $pagination.pagination;

    $('.rcrprev').click(function() {
        if (pnator("getCurrentPage") === 1)
            pnator("selectPage", pnator("getPagesCount"));
        else
            changePage('prev');
    });

    $('.rcrnext').click(function() {
        if (pnator("getCurrentPage") === pnator("getPagesCount"))
            pnator("selectPage", 1);
        else
            changePage('next');
    });

    function changePage(direction) {
        pnator(direction + 'Page');
    };
})();
```

That closure's not required of course, you can just adapt it to the rest of your code.
